name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Run script in virtualenv one
        run: make one
      - name: Run tests
        run: make tests
      - name: Clean up
        run: make clean
