name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements_test.txt
      - name: Run tests
        run: coverage run -m pytest
        working-directory: ./src
      - name: Report on results
        run: coverage report -m
        working-directory: ./src
      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        with:
          workingDirectory: ./src
          coverageCommand: coverage xml
          coverageLocations: coverage.xml:coverage.py

  coveralls_finish:
    needs: commit
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
