name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install tox
      - name: Run script in virtualenv one
        run: make one
      - name: Run tests
        run: make tests
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
          base-path: 'src/'
        env:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: ./src/coverage.xml
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: true
          path_to_write_report: ./src/codecov_report.txt
          verbose: true
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: src/coverage.xml

  coveralls_finish:
    needs: commit
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
      env:
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
